#!/usr/bin/env sh
set -eu

# keep forgetting to do this
# not perfect (will also apply any unstaged changes)
# but there should not be unstaged changes with my workflow
aerospace reload-config

# Update configuration files
make -C "$(git rev-parse --show-toplevel)"
