enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[mode.main.binding]
alt-shift-w = 'focus --boundaries-action wrap-around-the-workspace up'
alt-shift-a = 'focus --boundaries-action wrap-around-the-workspace left'
alt-shift-s = 'focus --boundaries-action wrap-around-the-workspace down'
alt-shift-d = 'focus --boundaries-action wrap-around-the-workspace right'

alt-q = 'move-node-to-workspace prev'
alt-e = 'move-node-to-workspace next'

alt-w = 'move up'
alt-a = 'move left'
alt-s = 'move down'
alt-d = 'move right'

alt-f = 'fullscreen'

# cmd because need alt-4 for $
cmd-alt-1 = 'workspace 1'
cmd-alt-2 = 'workspace 2'
cmd-alt-3 = 'workspace 3'
cmd-alt-4 = 'workspace 4'
cmd-alt-5 = 'workspace 5'
cmd-alt-6 = 'workspace 6'
cmd-alt-7 = 'workspace 7'
cmd-alt-8 = 'workspace 8'
cmd-alt-9 = 'workspace 9'
cmd-alt-0 = 'workspace 10'
